### ISSUE TITLE
Constrained calls to IComparable<T> instead of virtual calls IComparer<T>

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads#100]
This commit https://github.com/Spreads/Spreads/commit/91516d214380583998bd91d3caadd365eec0fe36 demonstrates the effect of virtual calls. In Spreads, especially [SortedMap](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Collections/Collections/SortedMap.fs#L65), 99% use cases are `DateTime` or `Int64`.

Need to do something with it. One idea is to use a concrete class KeyComparer<T> inside SM. But then will need reflection and implementation caching by type `T` to avoid constraining `TKey` to `IComparable`. With this JIT optimizations could easily break.

E.g. not sure if the code below will be better optimized by JIT vs IComparer. Maybe should just wait until devirtualization is shipped.

```
public class KeyComparer<T> : IComparer<T>
{
    // Set this to ConstrainedKeyComparer<T> if T implements IComparable<T>,
    // otherwise fallback to default IComparer or a provided one (not implemented here)
    public static KeyComparer<T> Instance;

    public int Compare(T x, T y)
    {
        throw new NotImplementedException();
    }
}

public sealed class ConstrainedKeyComparer<T> : KeyComparer<T> where T : IComparable<T>
{
    public new int Compare(T x, T y)
    {
        return x.CompareTo(y);
    }
}

```

**Comment by buybackoff** [comment]
It works. Should use this in SortedMap, 20% gain on `long` comparison.

**Comment by buybackoff** [comment]
Interesting, adding a new implementation with `new` keyword for `CompareTo` makes this `new` method 3 times faster for `long`, but the generic cached version for `long` becomes much slower.

```
    public sealed class ConstrainedKeyComparerLong : KeyComparer<long>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public new int Compare(long x, long y)
        {
            return x.CompareTo(y);
        }
    }
```

Just using `override` keeps performance of the generic cached `ConstrainedKeyComparer<T>` for `long` unchanged from the initial tests:

```
    public sealed class ConstrainedKeyComparerLong : KeyComparer<long>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int Compare(long x, long y)
        {
            return x.CompareTo(y);
        }

        public override bool IsDiffable => true;
    }
```

**Comment by buybackoff** [comment]
For cursors and ZipN especially this could be substantial. We should assume that all containers in Spreads use `KeyComparer` and not `IComparer` (fallback to a wrapper inside their implementation if a custom IComparer was provided).

**Comment by buybackoff** [comment]
F# ignored MethodImpl.AggresiveInlining and probably still does https://github.com/Microsoft/visualfsharp/issues/1637 

Such a surprise given that it has nothing to do with F# itself, it turns out that it just doesn't let JIT to do its work. This is my first usage of that profiler, not sure if a method is shown it means it is not inlined, but in PerfView that was the case.

Also there are weird FSharp.Core method calls in the most trivial method that together cost more that an Interlocked method. Maybe `object.ReferenceEquals` will fix that.

![image](https://cloud.githubusercontent.com/assets/489852/24680921/6f74ee1c-199b-11e7-9879-27a96bc80cfe.png)

It is interesting how expensive comparer stuff is given that it is just DateTime/long arithmetic.

**Comment by buybackoff** [comment]
Another specialization idea
-------------------------------

Containers are classes with inheritance hierarchy and virtual calls are inevitable (however, for sealed classes they could be devirtualized eventually). But everything inside public methods should be inlineable.

E.g. for `SortedMap<K,V>` we could create a child class `SortedMap<K,V,TComparer>`, remove constructors from `SortedMap<K,V>` and use static `Create(...)` methods to return specialized implementations and fall back to `KeyComparer` when no custom comparer is given and to `IComparer` when `K` is not `IComparable`.

**Comment by omariom** [comment]
You can create generic `Compare<TKey>` method specialized for DateTime and a few other value types and falling back to the provided `IComparer<T>` instance.

**Comment by buybackoff** [comment]
@omariom Kestrel guys just removed generic dispatch three days ago as "being orders of magnitude slower", but will try this approach as well.

**Comment by omariom** [comment]
I mean something like:
```C#

private int Compare(TKey key1, TKey key2)
{
    if (comparer != null)
        return comparer.Compare(key1, key2);
 
    if (typeof(TKey) == typeof(int)) return ((int)(object)key1) - ((int)(object)key2);
    if (typeof(TKey) == typeof(DateTime)) return ((DateTime)(object)key1).CompareTo(((DateTime)(object)key2));
 
    return Comparer<TKey>.Default.Compare(key1, key2);
}
```

It worked even in the old JIT.

**Comment by buybackoff** [comment]
I completely forgot about this Vector-like approach for a comparer, thanks! This should be fast, but I so much dislike this `(object)` casting in general.

**Comment by omariom** [comment]
JIT is clever enough not to box it.
For example, for `int` it should generate code as if it were:
```C#
private int Compare(int key1, intkey2)
{
    if (comparer != null)
        return comparer.Compare(key1, key2);
    return key1 - key2;
}
```

**Comment by buybackoff** [comment]
Is this documented that it avoids boxing? I knew it was very fast, but have thought that it is still a very short-lived object that contributes to GC0.

**Comment by omariom** [comment]
I checked the  generated assembly in VS debugger. 
It was a few years ago but I don't think  RyuJIT haven't inherited all the tricks of the old JIT :)

You can test in BenchmarkDotNet. It shows the allocations.

**Comment by buybackoff** [comment]
Thanks for the info! Didn't have time to run PerfView on such things yet :)

**Comment by buybackoff** [comment]
It is 3 times slower than statically cached virtual calls (even without `_comparer = null` check). Current implementation with statically cached implementations is faster that interfaces and I will stick with it. Unless I messed up with this experimental implementation.

**Comment by omariom** [comment]
I can't read F#, sorry :)
I meant using that `Compare` method right in your SortedMap. Not in another implementation of IComprarer.

**Comment by buybackoff** [comment]
I will use the private compare method in SortedMap for better inlining if needed, but with this small change `typeof(T) == typeof(int)` the KeyComparer became 3 times faster!

**Comment by omariom** [comment]
👍

**Comment by buybackoff** [comment]
@omariom  Thanks for help! By using the new sealed `KeyComparer` instead of `IComparer` all cursors and ZipN will already be visibly faster even without any other changes.

**Comment by buybackoff** [comment]
@omariom It was kind of cool that you starred this repo and followed me, I have been watching your contributions and comments quite a lot in corefx, coreclr, Aeron... (e.g. static readonly being JIT compile-time constant, it's a big one 😄 [fixed](https://github.com/Spreads/Spreads/commit/4355585f49973ead9e8bce677aaed95fdb131fc1) this yesterday here)

As you are very experienced and interested in nano-optimizations, do you any idea why AggressiveInlining attribute could really [hurt](https://github.com/Spreads/Spreads/commit/054c375752df3dbb58284dfb927716c5dc59c791) for sealed classes/methods that do quite trivial job? I have been working on specializing Spreads cursors (aka advanced IEnumerators) to concrete types and found the case when the attribute was just killing performance compared to a lambda. It looks like simple lambdas are very efficient, but a profiler shows that they are not inlined anyways... So I kind of lost here - why forcing inlining doesn't help?

**Comment by omariom** [comment]
Thanks, your project is interesting.

Regarding inlining, you need too look at the generated assembly. Too much of inlining can sometimes confuse JIT.

**Comment by buybackoff** [comment]
Btw, which tool their are using to see what JIT is doing? I have seen many times that benadamans and jcotas post some pretty interesting diagnostics from JIT, but it's not PerfView or dotTrace. I still having hard times to read asm and probably this level is too deep for me, but I want to make friends with JIT as seen from .NET at least.

**Comment by omariom** [comment]
The easiest way is to just switch to assembly view  in VS with Ctrl-Alt-D.
But [jit dumping](https://github.com/dotnet/coreclr/blob/master/Documentation/building/viewing-jit-dumps.md) provides more details.

Assembly is easy  to read. Much easier than F#, believe me :)

**Comment by omariom** [comment]
Have you thought about arithmetic operation as another generic parameter for ArithmeticSeries?
Like this:
```C#
interface IArithmeticOperation<T>
{
    T Apply(T first, T second);
}

struct AddOp<T> :  IArithmeticOperation<T>
{
    public T Apply(T first, T second)
    {
        if (typeof(T) == typeof(int))
        {
             return (T)(object)((int)(object)first + (int)(object)second);
        }
        else if (typeof(T) == typeof(double))
        {
             ....
        }
    }
}
```
It is important to make them structs.

**Comment by buybackoff** [comment]
Will test this, thanks!

**Comment by omariom** [comment]
And AggressiveInlining on `Apply`.

**Comment by buybackoff** [comment]
That works great! 👍 Your help is really awesome and makes this lib super fast  😄

**Comment by buybackoff** [comment]
@omariom FYI, I have [implemented](https://github.com/Spreads/Spreads/commit/172087ea61858f2fd10f2f469e9c450273b402d3) an [unsafe constrained call](https://github.com/Spreads/Unsafe) to `IComparable<T>` interface method via IL and use `static readonly bool` to cache info if a type `T` implements this interface. By doing so, comparison for any type that implements the interface should be as fast as using `typeof(T) == typeof(...)` pattern (tested for ints).

Do you think this is "safe", i.e. correct and won't blow up under some circumstances?

**Comment by omariom** [comment]
An interesting approach. Is the perf the same for primitives?

**Comment by omariom** [comment]
I am not sure it will work in AOT scenarios.

**Comment by omariom** [comment]
I mean jit time constants don't work in aot

**Comment by omariom** [comment]
Even in jit case that static read only bool variable must be initialized before the target method is compiled

**Comment by buybackoff** [comment]
Perf is the same for `int`s. If this static field is in the same class where the methods are and it has an initializer, it seems that it will always be initialized before any access to the methods.

I don't get the thing about AOT - is it specific to the unsafe approach, or any constants are not optimized, including `typeof(T) == typeof(...)`?

**Comment by omariom** [comment]
I will check what it compiles to when crossgened later today. But even if `IsIComparable` initialization check and ```if (IsIComparable)``` are not removed from the generated code this approach is quite novel (at least for me :smile:) and can be used as the last resort even in AOT scenario.

**Comment by buybackoff** [comment]
That was an experiment and it worked 😄 If it doesn't work always then at least I could keep `typeof(T) == typeof(...)` pattern for hot paths and use `Unsafe` as a fallback for `IComparable`s. However, the `Comparer<T>.Default` already uses the interface if it is present and I haven't tested its performance yet - but it is an abstract class and will have the virtual overheads. Will later test what is cheaper - not `readonly` `IsIComparable` with Unsafe or virtual call to the default `Comparer<T>`. Probably not eliminated single `if` check will still be faster...

**Comment by omariom** [comment]
This is what is generated for `int`
```C#
    static class StaticComparer<T>
    {
        public static readonly bool isIComparable = typeof(IComparable<T>).IsAssignableFrom(typeof(T));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int Compare(T x, T y)
        {
            if (isIComparable)
            {
                return Unsafe.CompareToConstrained(x, y);
            }
            return 33;
        }
    }
```
```ASM
; Lcl frame size = 40

G_M20638_IG01:
       57                   push     rdi
       56                   push     rsi
       4883EC28             sub      rsp, 40
       8BF9                 mov      edi, ecx
       8BF2                 mov      esi, edx

G_M20638_IG02:
       48B9B0566D6FFC7F0000 mov      rcx, 0x7FFC6F6D56B0
       BA01000000           mov      edx, 1
       E85238275F           call     CORINFO_HELP_CLASSINIT_SHARED_DYNAMICCLASS
       803D4B67E8FF00       cmp      byte  ptr [reloc classVar[0x6f6d6c08]], 0
       741A                 je       SHORT G_M20638_IG06
       3BFE                 cmp      edi, esi
       7D07                 jge      SHORT G_M20638_IG03
       B8FFFFFFFF           mov      eax, -1
       EB0D                 jmp      SHORT G_M20638_IG05

G_M20638_IG03:
       3BFE                 cmp      edi, esi
       7E07                 jle      SHORT G_M20638_IG04
       B801000000           mov      eax, 1
       EB02                 jmp      SHORT G_M20638_IG05

G_M20638_IG04:
       33C0                 xor      eax, eax

G_M20638_IG05:
       EB05                 jmp      SHORT G_M20638_IG07

G_M20638_IG06:
       B821000000           mov      eax, 33

G_M20638_IG07:
       4883C428             add      rsp, 40
       5E                   pop      rsi
       5F                   pop      rdi
       C3                   ret      

; Total bytes of code 77, prolog size 6 for method CoreClrTestNew.Program:TestStaticComparer(int,int):int
```
The old approach gives this:
```ASM
       8BC1                 mov      eax, ecx
       2BC2                 sub      eax, edx
       C3                   ret  
```

**Comment by buybackoff** [comment]
Is this for AOT only? I still read F# better than assembly - even though
you said the assembly is simpler :) Have you run any performance
benchmarks?

**Comment by buybackoff** [comment]
I mean - for JIT on my machine perf is the same for `int`s (even if there are more/different instructions), but I don't know yet how to use crossgen - have read after your post, but not tried. My 99% use case now is .NET451+, another 1% is .NETCore on Ubuntu (the share of which will grow gradually), so AOT/mobile is not a major concern. But after your feedback I will put back the `typeof(T)==...` pattern for the build-in primitives anyway, since it is free. Thanks!

**Comment by omariom** [comment]
It is JIT. I haven't managed to crossgen the test assembly but AFAIK the trick with static readonly fields doesn't work for crossgen, so it will be the same. 

I think the diff is small because this part is not the main contributor to perf. And it is still better than virtual dispatch to the  default comparer's `Compare`.
