### ISSUE TITLE
NuGet won't let 1.0 until all dependencies are stable

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads#119]
`System.Memory`, `S.R.CS.Unsafe` and `S.N.Vectors` are in preview, the first ones have been moved from MyGet to NuGet. `System.Buffers.Primitives` is used from MyGet as a .dll in `Spreads.Utils` package and will likely be moved inside `System.Buffers` when stable. It looks like the roadmap for .NET Core 2.0 is set to Q3 and it is also a good target to get Spreads to 1.0.

Also should retarget to .NET Standard 2.0 from 1.6 or check if all performance optimizations mentioned in the recent [blog post](https://blogs.msdn.microsoft.com/dotnet/2017/06/07/performance-improvements-in-net-core/) will work from 1.6 as well. However, the most relevant ones (e.g. KeyComparer) are already done manually in Spreads and only the native `Span` is a big thing.

**Comment by ElanHasson** [comment]
When will be able to use the 1.0 version from .Net Standard v2.0? The NuGet packages are referencing  old dependencies are not easily usable. 

```
Install-Package : Detected package downgrade: Spreads.Core from 1.0.0-build1708301507 to 1.0.0-alpha2. Reference the package directly from the project to select a different version. 
 Test.Mechanisms -> Spreads.Collections 1.0.0-alpha2 -> Spreads.Core (>= 1.0.0-build1708301507) 
```


Any possibility you could publish the alpha packages so they can be more easily consumed via nuget ?


Thanks!

**Comment by buybackoff** [comment]
The guys from MSFT renamed Buffers to Memory back (they renamed Memory to Buffers earlier this year, now changed everything back) and made other changes that take time to update. I am tired of them actually releasing the Span/Buffers/Memory stuff so slowly and do not want to spend time integrating with changing APIs before they release a stable version. It is still in preview now: https://www.nuget.org/packages/System.Memory.

But from your error it looks like NuGet thinks that `...-alpha` is a downgrade from `...-build...` because it orders alphabetically. Spreads alpha is already .NET Core 2.0, but uses preview packages that I will update as soon (or as late) as MSFT releases them.

**Comment by buybackoff** [comment]
Maybe I should change `...-alpha` to `...-preview` to make NuGet happy

**Comment by buybackoff** [comment]
System.Memory is the only package left and it is `preview2`, they are preparing to make it stable with .NET Core 2.1 big release in 1Q2018, but probably they won't change everything again. Will have a look certainly before 1Q2018, but don't know when.

**Comment by ElanHasson** [comment]
Thanks Victor. Appreciate the quick response.

Please let me know if/when you make a change and I'll retry and confirm.

**Comment by ElanHasson** [comment]
Hi Victor-- any updates on this?

**Comment by buybackoff** [comment]
Latest MyGet preview is as of end of September, earlier than the latest source code in corefx, and API differ. I just won't waste my time util they publish stable API preview package on NuGet.

**Comment by buybackoff** [comment]
Actually I have updated the project and published NuGet. Mostly Ctrl+H to replace Buffer to Memory again. Builds that end with `R` (e.g. https://www.nuget.org/packages/Spreads.Core/1.0.0-build1711180306R) are Release ones, they do not have debug symbols since Spreads is very optimized for inlining and symbols are of little use.

**Comment by buybackoff** [comment]
Should work now. Removed MyGet, targeting netstandard2.0, net461 and netcoreapp3.0 (Spreads.Core).
