### ISSUE TITLE
error NU1102: Unable to find package System.Memory with version (>= 4.5.0-preview2-25707-02)

### ISSUE THREAD

**Issue by wklm** [Spreads/Spreads#125]
Hey @buybackoff,

many thanks for open sourcing this lib!
In `Spreads.Core.csproj` you're including the `System.Memory` package: 
` <PackageReference Include="System.Memory" Version="4.5.0-preview2-25707-02" />`

However it looks like the only accessible version is: [4.4.0-preview1-25305-02](https://www.nuget.org/packages/System.Memory/4.4.0-preview1-25305-02#)

Using it causes build errors:
```
Serialization/BinarySerializer.cs(55,56): error CS0246: The type or namespace name 'Memory<>' could not be found (are you missing a using directive or an assembly reference?) 
...
```

 Did you encounter similar issues? Would you have any tips how to deal with this?

cheers,
Wojtek

**Comment by buybackoff** [comment]
Hi! The dependency is from MyGet, but even there they have changed versions and the referenced one is not there. The one from NuGet won't work, but you could try a latest one from here: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory

Not sure if they haven't change the API *again* after last time I synced with the library.

**Comment by wklm** [comment]
Looks like it's under active development: https://github.com/dotnet/corefx/tree/master/src/System.Memory

Well, in this case I would rather wait until the publish an official, stable package. Thanks!

**Comment by buybackoff** [comment]
Yes, that package blocks Spreads development. It is set for release in .NET
Core 2.1 in 1Q18.

**Comment by wklm** [comment]
For those who will come across the same problem, the latest correctly working library version seems to be `0.5.1` :+1:

**Comment by buybackoff** [comment]
Omg 0.5.1! The latest NuGet ones (1.0-buildXxx) should work but they depend on MyGet, haven't tried to run it on a clean PC without cached packages, do not know if Nuget keeps track of the package origin. Master should build OK with nuget.config. There were so many goodies since 0.5.1 and performance increased cumulatively by 10x or so. It is a shame that there is still no fresh System.Memory preview on NuGet. Spreads is not the only package suffering from this,  e.g. NSec new high perf libsodium package is also waiting for it.

**Comment by buybackoff** [comment]
I used to have a separate package Spreads.Utils where I put dlls from MyGet with S.R.CS.Unsafe, System.Buffers and System.Memory, however all but the last are released and I hoped S.M would be at least alpha soon. So I removed that manual temp package, even though it just worked.

**Comment by buybackoff** [comment]
This should work now.
