### ISSUE TITLE
Can not install via NuGet

### ISSUE THREAD

**Issue by tfwnicholson** [Spreads/Spreads#126]
When trying to install via NuGet (version 2.12 targeting .NET 4.7 using Mono 5.10 on Ubuntu 16.04) I consistently get the error:
```
Adding Spreads...
Attempting to resolve dependency 'Spreads.Collections (≥ 0.6.1)'.
Attempting to resolve dependency 'FSharp.Core (≥ 3.1.2.5)'.
Attempting to resolve dependency 'Spreads.Core (≥ 0.6.1)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 9.0.1)'.
Attempting to resolve dependency 'System.Numerics.Vectors (≥ 4.1.1)'.
Attempting to resolve dependency 'System.Buffers (≥ 4.0.0)'.
Attempting to resolve dependency 'System.Threading.Tasks.Extensions (≥ 4.0.0)'.
Downloading System.Threading.Tasks.Extensions 4.0.0...
Attempting to resolve dependency 'System.Slices (≥ 0.1.0-e170111-4)'.
Unable to resolve dependency 'System.Slices (≥ 0.1.0-e170111-4)'.
```

**Comment by wklm** [comment]
Hey @tfwnicholson,

I assume this issue is related to: https://github.com/Spreads/Spreads/issues/125

Cheers,
Wojtek

**Comment by buybackoff** [comment]
Also please do not try to install "stable" NuGet versions, they are hopelessly outdated. The last NuGet could theoretically resolve MyGet dependency on System.Memory if you add [corefx](https://dotnet.myget.org/gallery/dotnet-core) source from there.

**Comment by tfwnicholson** [comment]
Thanks for the response. I solved by adding a nugget source for corefx. If not installing via NuGet then how should one install?

**Comment by buybackoff** [comment]
> If not installing via NuGet then how should one install?
I mean do not install the old versions that do end end with any suffix and which NuGet considers "stable" (0.5.x and earlier). Latest packages has `-buildXXX` suffix and NuGet shows them as pre-release. They depend on MyGet though.

**Comment by lexruster** [comment]
For me, it worked after manual installation of latest System.Memory from CoreFX (in my case 4.5.0-preview2-26125-01) 
And after that latest install of Spreads

**Comment by mokeyish** [comment]
I have found this problem too...

**Comment by buybackoff** [comment]
Now all NuGet dependencies are on the standard NuGet.org server/feed, please try again.
https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/
