### ISSUE TITLE
[Question] How to create a series in C#

### ISSUE THREAD

**Issue by ElanHasson** [Spreads/Spreads#130]
Hi @buybackoff,

Thanks for putting this library together. It seems pretty amazing! 

I'm hoping you could point me to an example on how to create a new series in C#.

I'm looking to generate the SMA from a live data stream of market data order matches and I'm not sure how to approach this using Spreads.

Thanks

**Comment by buybackoff** [comment]
Hi @ElanHasson ,

I will return this library in the coming weeks, especially given .NET Core 2.1 with Span & Co is already in Preview 2. Hopefully will add minimal docs. I'm going to use it for a new big trading-related project.

In the meantime, you may look into unit tests. Especially the one that simulate real-time data.

**Comment by ElanHasson** [comment]
Thanks @buybackoff 

I did find  https://github.com/Spreads/Spreads/blob/50af92118824acf3d7cef61b70099c1573f3116c/tests/Spreads.Tests.Profile/Example.fsx#L60

and based on that example was able to build a series based off of a SortedMap<DateTime, decimal>.

My F# experience is basic at best, but it seems in F# you can use the `/` and `-` operators on a SortedMap and a Series.

How would this translate to C#?

(this.Data / sma - 1.0).Map(fun deviation -> double <| Math.Sign(deviation))

My objective is to be able to plot the SMA as a line.

**Comment by buybackoff** [comment]
In C# you should be able to use all operators on series as well. (implemented here in C# https://github.com/Spreads/Spreads/blob/master/src/Spreads.Core/Series'2%20(Base).cs plus in several other places, required a lot of boilerplate).

A direct transaltion to C# should work (not checked the code below)
```
 var targetPosition = (quotes / sma - 1.0).Map(deviation => (double)Math.Sign(deviation)) ;
```

**Comment by ElanHasson** [comment]
I see my issue, it was because I needed to use 1.0 vs 1 which messed with the expected data type of double.

From what I've gathered, the Series object is meant to operate over existing IEnumerables and not actually store the data itself.

Is this correct?

**Comment by buybackoff** [comment]
This repo has in-memory implementation of containers, basically
`SortedMap<TK,TV>` as the main class. The rest is math + online operators +
zipping logic over abstract BaseSeries. You only need to implement ICursor
to create a series implementation with any underlying container/storage.
