### ISSUE TITLE
Last build Spreads and Spreads.Extension not compatible ?

### ISSUE THREAD

**Issue by Ales999** [Spreads/Spreads#149]
Hello All,

Simple Code:
        static void Main(string[] args)
        {
            var sm = new SortedMap<DateTime, float>();
	  /*  skip small code to insert data  */
            var quotes = sm.ReadOnly();
            var SMA = quotes.SMA(20, true); 
         /* skip code*/
        }

![2018-12-26 13 55 43](https://user-images.githubusercontent.com/367257/50440263-26b7fa80-0917-11e9-98bc-80b12848cd15.png)

This is Work!

Then, If added package 'Spreads.Extension' package ( v. 0.6.0-alpha5  )then in line 
var SMA = quotes.SMA(20, true);  is error:

Error | CS0012 | The type 'Series<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Spreads.Collections, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

![2018-12-26 14 09 45](https://user-images.githubusercontent.com/367257/50440461-308e2d80-0918-11e9-9bf4-d40cda70fe4b.png)

PS Вероятно можно и на родном языке :-)

**Comment by Ales999** [comment]
I was trying to find how to save the added my data to disk, for use later. What is now the priority method for this. Previously used in the examples, in F#, as "open Spreads.Storage", and "let store = new SeriesStorage (SeriesStorage.GetDefaultConnectionString (" TAQSample.db ")));"
How to start saving now, if 'using Spreads.Storage' not available?
Tell me where to start searching for a starting point to save now.

**Comment by buybackoff** [comment]
Storage is no longer in this repository. It will hopefully be published "soon" as a separate project.

**Comment by Ales999** [comment]
Ah, ok. Waiting ....
