### ISSUE TITLE
Build from master fails: lib\Utf8Json missing sources

### ISSUE THREAD

**Issue by dpavsrtrl** [Spreads/Spreads#157]
tried to build running build.cmd

Spreads.Core.csproj build fails because of missing sources in lib\Utf8Json

**Comment by dpavsrtrl** [comment]
I realized this uses git submodules. Need to do this from top folder:

`git submodule update --init --recursive`

**Comment by buybackoff** [comment]
I still hope that Utf8Json  upstream will become alive so do not want to just import code as is, but due to weird dependency chain it must be that way for now. With netcore3.0 I will probably use their new fast JSON readers/writers if they are close in performance to reduce dependency.
