### ISSUE TITLE
ML.NET integration

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads#158]
ML.NET 0.10 introduced this as a separate package. Looks like Spreads had the cursor from the very beginning. Need to sort out schema thing and maybe learn something useful before implementing Matrix and Frame.

https://github.com/dotnet/machinelearning/tree/master/src/Microsoft.Data.DataView

**Comment by nextnode-managedcode** [comment]
I would like to work on this issue.

**Comment by buybackoff** [comment]
Spreads series and other containers should not implement IDataView interface or depend on ML.NET in any other way. Actually integration with R.NET still looks more interesting, and Infer.Net is more relevant for streaming data than ML.NET.

A separate project could have bridge implementation of interfaces/objects required for ML.NET and an extension method `public static IDataView AsDataView(this ISeries...)`

**Comment by buybackoff** [comment]
No binary dependencies, maybe extensions pack NuGet later
