### ISSUE TITLE
How to setup for development

### ISSUE THREAD

**Issue by dpavsrtrl** [Spreads/Spreads#159]
I can build with build.cmd, but now I'd like to figure out the code, run tests, etc. I tried with latest VS 2017, then with 2019 Preview. Build fails. Maybe it's something simple I'm missing:

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\workspace\Spreads\src\Spreads.Collections\bin\Debug\netstandard2.0\Spreads.Collections.dll' could not be found	Spreads (netstandard2.0)	C:\workspace\Spreads\src\Spreads\CSC	1	Active
Error	CS0006	Metadata file 'C:\workspace\Spreads\src\Spreads.Collections\bin\Debug\net461\Spreads.Collections.dll' could not be found	Spreads (netstandard2.0)	C:\workspace\Spreads\src\Spreads\CSC	1	Active
Error	CS0006	Metadata file 'C:\workspace\Spreads\src\Spreads.Collections\bin\Debug\netstandard2.0\Spreads.Collections.dll' could not be found	Spreads.Core.Tests (netcoreapp3.0)	C:\workspace\Spreads\tests\Spreads.Core.Tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\workspace\Spreads\src\Spreads\bin\Debug\netstandard2.0\Spreads.dll' could not be found	Spreads.Core.Tests (netcoreapp3.0)	C:\workspace\Spreads\tests\Spreads.Core.Tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\workspace\Spreads\src\Spreads.Collections\bin\Debug\netstandard2.0\Spreads.Collections.dll' could not be found	Spreads.Core.Run	C:\workspace\Spreads\tests\Spreads.Core.Run\CSC	1	Active
Error	CS0006	Metadata file 'C:\workspace\Spreads\tests\Spreads.Core.Tests\bin\Debug\netcoreapp3.0\Spreads.Core.Tests.dll' could not be found	Spreads.Core.Run	C:\workspace\Spreads\tests\Spreads.Core.Run\CSC	1	Active
Error	CS0006	Metadata file 'C:\workspace\Spreads\src\Spreads\bin\Debug\netstandard2.0\Spreads.dll' could not be found	Spreads.Core.Run	C:\workspace\Spreads\tests\Spreads.Core.Run\CSC	1	Active
Error	FS0078	Unable to find the file 'C:\workspace\Spreads\src\Spreads.Collections\bin\Debug\netstandard2.0\Spreads.Collections.dll' in any of C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1 C:\workspace\Spreads\tests\Spreads.Collections.Deedle.Tests C:\Users\dpavlenkov\.nuget\packages\fsharp.core\4.3.4\lib\netstandard1.6	Spreads.Collections.Deedle.Tests (netcoreapp2.1)	C:\workspace\Spreads\tests\Spreads.Collections.Deedle.Tests\FSC	1	Active
Error	CS0006	Metadata file 'C:\workspace\Spreads\src\Spreads.Collections\bin\Debug\netstandard2.0\Spreads.Collections.dll' could not be found	Spreads.Collections.Tests (netcoreapp2.1)	C:\workspace\Spreads\tests\Spreads.Collections.Tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\workspace\Spreads\src\Spreads\bin\Debug\netstandard2.0\Spreads.dll' could not be found	Spreads.Collections.Tests (netcoreapp2.1)	C:\workspace\Spreads\tests\Spreads.Collections.Tests\CSC	1	Active
Error	CS0246	The type or namespace name 'BinarySerializationAttribute' could not be found (are you missing a using directive or an assembly reference?)	Spreads.Core.xUnit	C:\workspace\Spreads\tests\Spreads.Core.xUnit\Serialization\SerializationTests.cs	24	Active
Error	CS0246	The type or namespace name 'BinarySerialization' could not be found (are you missing a using directive or an assembly reference?)	Spreads.Core.xUnit	C:\workspace\Spreads\tests\Spreads.Core.xUnit\Serialization\SerializationTests.cs	24	Active
Error	NU1605	Detected package downgrade: Microsoft.CSharp from 4.6.0-preview.18571.3 to 4.5.0. Reference the package directly from the project to select a different version. 
 Spreads.Collections.Tests -> Spreads.Core -> Microsoft.CSharp (>= 4.6.0-preview.18571.3) 
 Spreads.Collections.Tests -> Microsoft.CSharp (>= 4.5.0)	Spreads.Collections.Tests	C:\workspace\Spreads\tests\Spreads.Collections.Tests\Spreads.Collections.Tests.csproj	1	
Error	NU1605	Detected package downgrade: System.Numerics.Vectors from 4.6.0-preview.18571.3 to 4.5.0. Reference the package directly from the project to select a different version. 
 Spreads.Collections.Tests -> Spreads.Core -> System.Numerics.Vectors (>= 4.6.0-preview.18571.3) 
 Spreads.Collections.Tests -> System.Numerics.Vectors (>= 4.5.0)	Spreads.Collections.Tests	C:\workspace\Spreads\tests\Spreads.Collections.Tests\Spreads.Collections.Tests.csproj	1	
Error		Visual Studio Container Tools requires Docker to be running before building, debugging or running a containerized project.

For more info, please see: http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	398	

`

**Comment by dpavsrtrl** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/25111447/52656904-5b7f1180-2ec5-11e9-8e62-c851c750b94b.png)

**Comment by buybackoff** [comment]
You need to build F# project explicitly probably. I disabled its automatic build because it's slow. But I thought it was part of local settings.

Also you may just unload all tests projects other that `...Core` and `...Core.Run`.

It used to work on CI server just recently, so `dotnet build` should work as well.

**Comment by buybackoff** [comment]
Azure Pipeline works as of now, so the project definitely builds from scratch on a fresh machine.

https://github.com/Spreads/Spreads/blob/master/azure-pipelines.yml.

As for Docker, you may also just unload the project. I use it sometimes to run code from `Spreads.Core.Run` on Ubuntu but there is nothing more there and I haven't touched that for a long time, maybe it's broken now.

**Comment by dpavsrtrl** [comment]
I was getting error NU1605: Detected package downgrade: System.Numerics.Vectors from 4.6.0-preview.18571.3 to 4.5.0. on Spreads.Collections.Test project

To fix that, went to project settings and set Treat warnings as errors to None.

**Comment by buybackoff** [comment]
As I said, all tests projects other than two `Core` ones are big technological debt and are unloaded in my VS for more than a year probably. I'm removing SortedMap, SortedChunkedMap, maybe will remove F# project completely or resurrect just `ImmutableSeries` based on trees. There were a lot of changes since last time I could build non-Core tests projects, I keep them to recover tests logic at some point.

BTW, I probably misunderstood from your original issue: are you interested in Utf8Json part here or the whole data processing functionality? The later undergoes a significant rewrite now (as well as significant performance boost) before I could finally ship a stable version.

**Comment by dpavsrtrl** [comment]
I'm interested in the whole thing, Utf8Json came up only because I couldn't build.

I ran Spreads.Collections.Tests and most of them failed, probably as expected from your comment.
Running Spreads.Core.Tests now. some are failing

My goal is to figure this thing out, and try to learn something. Apparently there's a lot of ideas coming together here

**Comment by buybackoff** [comment]
> Apparently there's a lot of ideas coming together here

Quite a few :)

Most of current development goes in `Spreads.Core/Collections/Internal+Experimental.` These will replace all container implementations and new ones - Matrix, Frame and Panel.

Main idea about lazy online evaluation will likely stay as is in `Spreads.Core/Cursors` and `Spreads.Core/Series'2/Series'3`. Main thing here is ZipCursor - but I myself cannot understand current implementation easily after fighting with it many months a couple of years ago, will rewrite in a clean and faster way as well.  Async multicast is in `AsyncCursor` and `BaseContainer` - together they implement async streams stuff.

Most other stuff it to make the whole thing extremely fast and efficient...

**Comment by buybackoff** [comment]
closed for #164
