### ISSUE TITLE
Unable clone submodule lib/FSharp.Data

### ISSUE THREAD

**Issue by Ales999** [Spreads/Spreads#160]
C:\Dev\ExtLibrary\ClonedFromGitHub>git clone https://github.com/Spreads/Spreads.git
Cloning into 'Spreads'...
remote: Enumerating objects: 1118, done.
remote: Counting objects: 100% (1118/1118), done.
remote: Compressing objects: 100% (635/635), done.
remote: Total 20624 (delta 759), reused 758 (delta 468), pack-reused 19506
Receiving objects: 100% (20624/20624), 16.91 MiB | 356.00 KiB/s, done.
Resolving deltas: **100%** (16287/16287), **done**.

cd Spreads

C:\Dev\ExtLibrary\ClonedFromGitHub\Spreads>git submodule update --init --recursive
Submodule 'lib/FSharp.Data' (https://github.com/fsharp/FSharp.Data.git) registered for path 'lib/FSharp.Data'
Submodule 'lib/Ix.NET' (https://github.com/Spreads/Ix.NET) registered for path 'lib/Ix.NET'
Submodule 'lib/Utf8Json' (https://github.com/Spreads/Utf8Json) registered for path 'lib/Utf8Json'
Cloning into 'C:/Dev/ExtLibrary/ClonedFromGitHub/Spreads/lib/FSharp.Data'...
Cloning into 'C:/Dev/ExtLibrary/ClonedFromGitHub/Spreads/lib/Ix.NET'...
Cloning into 'C:/Dev/ExtLibrary/ClonedFromGitHub/Spreads/lib/Utf8Json'...
**error**: unable to create file tests/FSharp.Data.DesignTime.Tests/expected/Csv,Titanic.csv,,passengerid = int ; Pclass -&gt; Class; Parch -&gt; ParentsOrChildren
= int&lt;meter&gt;;SibSp-&gt;SiblingsOrSpouse,True,True,True,,,.expected: Filename too long
Submodule path 'lib/Ix.NET': checked out '159a7d942ffbfa46fa1c20247dad00d20924a005'
Submodule path 'lib/Utf8Json': checked out 'e2c711abf6d5af52cbf7fde232be574d6730f9c5'
**Unable to checkout** '33e6e825bc2978eb9ce6dd880f31d9e60d452699' in submodule path **'lib/FSharp.Data'**

**Comment by buybackoff** [comment]
It's not used anymore, will remove it.
