### ISSUE TITLE
MPMCQueue can hang after int.maxvalue ops

### ISSUE THREAD

**Issue by birdimus** [Spreads/Spreads#178]
if (cell.Sequence < pos + 1)
and
if (cell.Sequence < pos)

can fail when pos rolls over to int.minvalue.  This causes an infinite loop.

In the source (1024 cores), the subtraction prevents this.
E.g. in C#
int dif = cell.Sequence- pos;
if(dif < 0)

There is also a cast to intptr, which, I don't fully grok the need for.

An example:
cell.Sequence = 2147483633
pos = -2147483648
dif = -15
however cell.Sequence > pos

**Comment by buybackoff** [comment]
Please, see the original MPMC repo https://github.com/alexandrnikitin/MPMCQueue.NET

Here was an experimental copy of that one.

Also there is a note in the original repo:

> Note: `ConcurrentQueue<T>` uses this algorithm since .NET Core and .NET >5.0. Please use that instead. Unless you want to modify this implementation for you needs, e.g. MPSC, SCMP.

**Comment by buybackoff** [comment]
Thanks for fixing the original!
