### ISSUE TITLE
Index calculation example from Readme

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads#24]
Implement the calculations of DJIA and SPX described in Readme for a single day of ticks. TAQParser example is a starting point: https://github.com/Spreads/Spreads/tree/master/tests/Spreads.TAQParser

**Comment by b-e-n-j** [comment]
Here's an attempt at turning the pseudo-code in the Readme into a real-time example (not from a parser).
It kind-of works, but frequently locks up in a spin inside ZipNCursor.doMoveNextContinuousTask
The more quoteSources I use, the more likely it is to lock up.
Any ideas what I'm missing?...

    #I "../bin"
    #r "Spreads.dll"
    #r "Spreads.Collections.dll"
    #r "Spreads.Extensions.dll"

    open Spreads
    open Spreads.Collections

    open System
    open System.Threading
    open System.Threading.Tasks

    let numQuoteSources = 2

    let cts = new CancellationTokenSource()
    let ct = cts.Token
    let rng = System.Random()

    let makeQuoteSource () : Series<DateTime, float> = // data is produced outside
        let mutable value = 1.0
        let sm = SortedMap()
        let now = DateTime.UtcNow
        let mutable trend = -1.0
        let mutable cnt = 0
        let gapMillisecs = int(rng.NextDouble() * 500.0 + 250.0)

        sm.Add(now, value)
        cnt <- cnt + 1
        if cnt % 40 = 0 then trend <- -trend

        let task = async {
                        while not ct.IsCancellationRequested do
                            do! Async.Sleep gapMillisecs
                            let time = DateTime.UtcNow
                            value <- value*(1.0 + rng.NextDouble()*0.002 - 0.001 + 0.001 * trend)
                            sm.Add(time, value)
                            cnt <- cnt + 1
                            if cnt % 40 = 0 then trend <- -trend
                    }
        Async.Start(task, ct)
        sm :> Series<DateTime, float>

    let arrayOfDiscreteSeries = Array.init numQuoteSources (fun i -> (makeQuoteSource ()).Repeat())

    let index : Series<DateTime, float> = 
        arrayOfDiscreteSeries.Zip(fun k vArr -> vArr |> Array.average)

    index.Do((fun k v -> 
                printfn "Index: %A = %f" k v
                ), ct)

    // Stop it gracefully
    //cts.Cancel()

**Comment by buybackoff** [comment]
I am fighting doMoveNextContinuousTask now, thanks for the snippet! Will add it as a unit test. The `doMoveNextContinuousTask` method is the most complex clumsy piece of code in the entire library with the issue number one #1 indicating that it doesn't always work.

One of the easiest solution was to always use a pivot - a discrete series which keys are used as a basis for inner join. Discrete Zip is much faster and and simpler.

**Comment by buybackoff** [comment]
arrayOfDiscreteSeries is arrayOfContinuousSeries in the example, `Repeat()` makes any series continuous.

**Comment by b-e-n-j** [comment]
Ah, yes so it is... I forgot to rename the variable when I moved the Repeat() from inside the index definition.

**Comment by buybackoff** [comment]
I must say that `doMoveNextContinuousTask` is broken now for sure on many cases, I have been reviewing and fixing ZipN today and this is the last part that is not fixed and is totally broken by other changes. Need to rewrite it completely and add some performance - it used to be very slow due to the heavy usage of `task{}` computation expression.

**Comment by buybackoff** [comment]
This works now inside [a test](https://github.com/Spreads/Spreads/blob/master/tests/Spreads.Tests/CircularTests.fs). ZipN is redesigned and presumably became slower for continuous case but closer to correct implementation. Some edge cases remain related to out-of-order data.

**Comment by b-e-n-j** [comment]
Thanks - it's looking happier now, and doesn't lock up.
Heap pressure is quite high though. If i run with 100 quotesources ticking 2x per sec each, it reaches 1GB in about a minute. 
If I run with just the quotesources ticking, but no index consuming them, it's stable at around 80MB commit size.
Any suggestions for what I can do?
I just sent pull request #28 which makes it easier to increase the number of quotesources in the test

**Comment by buybackoff** [comment]
Could you please try when one series is discrete? There is a completely new
logic for continuous zip and I will rework it further soon.

**Comment by buybackoff** [comment]
@b-e-n-j  yes, I see MoveNextAsync leaks like crazy and I know why! I will make Spreads implement [reactive streams](http://www.reactive-streams.org/) over the weekend: https://github.com/Spreads/Spreads/blob/master/src/Spreads.Core/Interfaces.cs

Current implementation with background tasks was lazy attempt to make tests pass and logic work correctly.

**Comment by b-e-n-j** [comment]
Excellent - I'll look forward to seeing that!

**Comment by buybackoff** [comment]
There are some [pieces](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Extensions/Generation/SortedMapGenerator.cs ) for series generation. If you can you could help with this and add standard method for series generation.

Also memory profiling is done [here](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Collections/Common/Utils.fs#L31) for benchmarks - we could use the same approach for profiling long-running examples like this one.

**Comment by buybackoff** [comment]
@b-e-n-j you could have a look! With 5000k sources and `Async.Sleep 1` I am having c.150k inputs/sec with stable memory - both continuous and discrete. That is before any optimization. Profiler shows that BinarySearch takes most time - we are searching over entire series now for continuous ones and there are no optimizations yet (or they do not work as expected in Repeat() cursor. I guess I commented them out recently.)

I believe one of the bottlenecks now is generation - `Async.Sleep 1` sleeps for c.15 msecs. Need a more aggressive generation and buffered sources that keep limited amount of past items and do not grow infinitely.

**Comment by buybackoff** [comment]
Was able to reach over 3+ MOps (peak 4.7) for continuous ZipN of 500 series with unbounded generation!

**Comment by b-e-n-j** [comment]
That's made a huge difference. I ran a test with 500 continuous series, ramping up the overall input rate. Output rate should be 1:1 with input, but it starts dropping away from linear after around 20 inputs per second, and maxes out around 70-80 per second. CPU and memory aren't troubled, so it's likely scheduling. 15.6ms windows time slice would be 64 per second, so possibly relevant. I'll try and take a look at the generation tomorrow eve if I get a chance - can you give me any pointers?
![indexrates](https://cloud.githubusercontent.com/assets/2520078/12380341/a525b40a-bd68-11e5-99c8-1a09c4b354ff.png)

**Comment by buybackoff** [comment]
I have fixed some bugs and logic, could you please re-run your numbers? With your generators, there was many out-of-order data points - when a point added has a key smaller than the largest zipped key. Such new ooo data points are ignored. This explains why it maxes out above 64. Your initial example was the most difficult edge case for continuous zip and it is not deterministic. I changed a generator so that each new key of any series is greater than all other keys.

**Comment by b-e-n-j** [comment]
The new version has made a small difference, but not huge...
![indexrates2](https://cloud.githubusercontent.com/assets/2520078/12387030/9a55b530-bdc1-11e5-9aea-95af1b74d0b0.png)
There shouldn't be any ooo data points within any of the quotesource series, because each quotesource is generated from a single chain of tasks. But the index series might see them arrive ooo, so you're right it's not deterministic. Ideally it wouldn't drop any data points. I can change the test to generate all the quotesources from a single chain of tasks, but this limits the use case.

**Comment by buybackoff** [comment]
Without dropping data points MoveNext() would have to go back to ooo points, recalculate values there, then continue and recalculate previous last key... while new data is arriving at the same time. With historical data, there is no such an issue, but for real-time processing new data is much more important. 

I had to discard the non-monotonic MoveNext behavior because it is counter-intuitive and the behavior would be weird. In ZipN implementation UnionKeys behave like that, but only to get values if we couldn't get them before, and this is hidden.

In the real world, all events are either serialized (e.g. all trades and event orders on exchanges have a numeric id) or not deterministic (some physical process). In the former case we could restore the total order by that id even if data arrives in parallel via UDP broadcast, in the later case we could serialize data ourselves by its arrival time. With many parallel tasks scheduler could be the issue - we cannot guarantee that a task with smaller key is executed before a task with a larger key, and the first key is then discarded.

Could you please show the code to generating the chart? Also could you please run this with the [new generator](https://github.com/Spreads/Spreads/blob/master/tests/Spreads.Tests/ReadmeTests.fs#L74)?

**Comment by buybackoff** [comment]
We should use a discrete pacemaker if possible, e.g. the most liquid instrument or index or a timestamp of all incoming events. That will be much more computationally expensive, but will not lose any data point. In continuous ZipN case such pacemaker is a union of all keys but it has ooo points. We could create a constructor that accepts a custom pacemaker.

**Comment by b-e-n-j** [comment]
So as you said the generator was naive. It was using TPL to schedule, and DateTime.UtcNow for its keys, and so a lot of the keys between different quotesources were colliding, limiting the output rate to the windows thread quantum.

**Comment by buybackoff** [comment]
The test works and memory allocation has significantly improved ( #34 ). Closing.
