### ISSUE TITLE
Reactive Streams

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads#29]
Spreads should implement http://www.reactive-streams.org/

There was a draft wok already here: https://github.com/Spreads/Spreads/blob/master/src/Spreads.Core/Interfaces.cs

Basically async is syntactic sugar and we already use IUpdatable interface which implements OnData, which is the same as OnNext for IObserver. Move... is subscriber requesting one item to a direction. We should extent RS to the directional case and add a method that accepts lookup direction together with count.

We could then write Spreads in any language easily and use Rx instead of Ix.

**Comment by scifral** [comment]
Victor, FYI, are you following the work in [corefxlab] (https://github.com/dotnet/corefxlab)?

In particular, the new API's in System.Threading.Tasks.Channels, System.Buffers, and the System.Span type seem to be well tailored for implementing a .NET variant of Reactive Streams.

I see for example, Tasks.Channels.IAsyncEnumerator<T> is defined, and Channels provide a Completion API as you've just implemented in Spreads.  Also, there's a ValueTask<T> type that can help reduce allocations for Tasks, where appropriate).

**Comment by buybackoff** [comment]
Thanks! I have looked though the files and cannot understand in 5 mins what the channels abstraction is for, e.g. compared to BlockingCollection and already existing implementations of its async variant? How it is useful for Spreads?

**Comment by buybackoff** [comment]
BTW, thanks for reminding me about ValueTask. I have watched the entire thread and now they have a separate library available for .NET 4.5. I want to try ValueTask for Spreads. However, I tried to benchmark TaskCompleteionSource vs its value-type equivalent AsyncTaskMethodBuilder and TCS was no slower and sometimes a bit faster. They say that .NET GC if the best in class for short lived objects, and a Task is usually short lived as well.

**Comment by buybackoff** [comment]
Note to self:
Inside OnNext lambda of a subscriber(subject) we just call MoveNext on the publisher's cursor, get the new value and push it downstream.

We do not need to rewrite Cursor logic in any way, it represents the core of Spreads. Both Observable and AsynEnumerable are additional installments on top of the core functionality to make it real-time. The implementation of MNA is already based on MN and signalling primitives that trigger calls to MN asynchronously.

A dual of MoveNextAsync could be implemented with an atomic counter "notConsumedValues": if it is above 0, we just call MN, else we branch into some logic. ZipN should be redesigned so that MNA just waits for a proper signal and pulls when data is ready using MN method.

**Comment by buybackoff** [comment]
Closed for  #40
