### ISSUE TITLE
Tuple elimination in TryFind... calls

### ISSUE THREAD

**Issue by scifral** [Spreads/Spreads#32]
Many calls to TryFindWithIndex are using idiomatic F# style which results in tuple allocation (see e.g. SortedDequeMap.TryFind; SortedDequeMapCursor.MoveNext).

Alternatively we can declare a mutable local and pass by ref, e.g.:

let mutable vr = Unchecked.defaultof<_>  
let idx = this.TryFindWithIndex(k, direction, &vr)

**Comment by buybackoff** [comment]
Good catch! That was written at the time I was seriously considering immutable functional maps as core data structures. Given it is internal we could just return [ValueTuple3](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Collections/Common/Types.fs#L42) or nested `KVP<bool,KVP<K,V>>` or whatever struct.

**Comment by buybackoff** [comment]
I like the last option with mutable because that requires minimum code rewrite and less copying of structs if the method returns false

**Comment by buybackoff** [comment]
Should remove all other occurrences of Try... pattern with F# tuples

**Comment by buybackoff** [comment]
@scifral see #34. I will close this since I have eliminated most of the occurrences. #34 will be the main place to aggregate all memory/GC related issues.

**Comment by buybackoff** [comment]
It turned out this was not necessary: https://github.com/Microsoft/visualfsharp/pull/335
