### ISSUE TITLE
Cross-platform

### ISSUE THREAD

**Issue by FaguiCurtain** [Spreads/Spreads#43]
Hi I've downloaded the package fine when i was using VS2015 on Win8.1

I just bought a new iMAC Retina, installed Xamarin to develop in F# and would like to install the package Spreads (together with Spreads.core and Spreads.Extensions)

However i get the following error message

Adding Spreads...
Attempting to resolve dependency 'Spreads.Core (≥ 0.3.5)'.
Attempting to resolve dependency 'FSharp.Core (≥ 3.1.2.5)'.
Attempting to resolve dependency 'Spreads.Extensions (≥ 0.3.5)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 7.0.1)'.
Attempting to resolve dependency 'NodaTime (≥ 1.3.1)'.
Adding 'Spreads.Core 0.3.5' to MyAlgos.
Could not install package 'Spreads.Core 0.3.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

in another forum someone suggested using Xamarin in Alpha version, i think i tried that, but it didn't work for me...

EDIT
actually i re-did all the steps from scratch. going into Xamarin, click for Check for Updates, switch to Alpha Channel, restart Xamarin, create a new solution from there and installing packages including Spreads.

maybe i did create the solution in the stable version before trying installing spreads in the alpha version thats why it didn't work the first time.

you can close the issue, but leave it here, some people may have the same problem.

Cheers

**Comment by wyoung** [comment]
NuGet tells you the problem:

> WARNING: Spreads Package contains PowerShell scripts which will not be run.

So, someone is going to have to replace those PowerShell scripts to make this work.

**Comment by buybackoff** [comment]
There should be no scripts. Probably some legacy stuff. However, Spreads.Extensions won't work yet because of native dependencies that I was too lazy to compile for Mac (I have one, but it has been low priority). I tested .Collections/.Core on Ubuntu and it just worked from source, haven't tested from Nuget. You are welcome to try to build from source. I won't do X-platform until I reach the beta milestone in the issues.

**Comment by buybackoff** [comment]
Also, Spreads is only 4.5. It won't work on 4.0. There is a workaround (as far as I remember, only Task.FromResult is used from 4.5 and there used to be an implementation of this for 4.5 in Utils.fs), but again, this is not something I want to spend time on. Just use 4.5.

**Comment by FaguiCurtain** [comment]
so you are using your library on Windows only ? may i ask your config ?
are you working in a financial institution / hedge fund ? they are using your software ? or its all for personal purpose ?

**Comment by buybackoff** [comment]
Yes, no, yes, yes, yes

**Comment by FaguiCurtain** [comment]
thanks for your answers making available professional quality library to everyone.
as for me, i'm a "retired" derivatives trader (doing that 20 years in an IB). but so far, i'm not thinking about program trading, i have got other interests, but who knows, i may change my mind later, and its good to know such libraries are available.

**Comment by buybackoff** [comment]
Closed for #18. Do not expect it soon.
