### ISSUE TITLE
Range method returns first value even if it is out of range

### ISSUE THREAD

**Issue by AlarrionovTV** [Spreads/Spreads#62]
[Test]
        public void testRange() {
            var sm = new SortedMap<DateTime, double>();
            sm.Add(new DateTime(2006, 1, 1), 1.0);
            var test = sm.Range(new DateTime(2005, 1, 1), new DateTime(2005, 1, 2)).ToSortedMap();
            Console.WriteLine(test.IsEmpty);
        }

**Comment by buybackoff** [comment]
fixed https://github.com/Spreads/Spreads/commit/b73c49f27b58904c8c1859dfa154bed2b5d06d40
