### ISSUE TITLE
Meta: Perhaps you can borrow some features from these projects

### ISSUE THREAD

**Issue by sirinath** [Spreads/Spreads#7]
- http://www.ankhor.com/
 - https://www.dadisp.com/
 - http://matrex.sourceforge.net/
 - https://www.quantrix.com/en/

**Comment by buybackoff** [comment]
Thanks! They look like heavy-weight platforms/frameworks/products, not libraries, and are outside the Spreads scope. We already use Spreads for discrete optimization and sensitivity in a way that a calculation has an array of input parameters and a target function (e.g. a strategy AUM), defined with Spreads and used as a pure function. Then we could brute force on parameters grid (Spreads performance often makes that viable) or use some smarter discrete optimization.

I am much more interested in https://pymc-devs.github.io/pymc/ for future development.
