### ISSUE TITLE
MSFT's Angara Bayesian library

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads#80]
Wonder how I missed it before: https://github.com/Microsoft/Angara.Statistics

It is in F# and MIT, but looks like no longer developed. Should scavenge for good parts before looking further into PyMC, Stan, R... Native F# implementation is great for this stuff! Could easily merge reusable blocks into Spreads as source.

**Comment by dsyme** [comment]
@buybackoff Angara is full of amazing stuff

It has been under development quite recently - perhaps they would accept new co-maintainers?

**Comment by buybackoff** [comment]
@dsyme It looks like their Flow project is active, do you know the status of the entire platforms and plans for future?  (cc: @msdvoits). If it is no longer actively developed, I think Math.Net is the most logical place to move it. (cc: @cdrnet) Or **fsprojects** to better expose it to F# community.

The Statistics project is just two self-contained files that probably do not require much maintenance.

**Comment by buybackoff** [comment]
Distribution generators are in Spreads.Collections - useful for .NET Core until Math.NET is there. Bayesian stuff is out of scope (better to use well documented and proven R packages).
